spring:
  profiles:
    active: production
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-163-228-109.compute-1.amazonaws.com:5432/dfcomeboave3jd
    username: fyyknypscirzdg
    password: btRK9jnZj1qcqOrZe8OBdnJjNn

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:postgresql://192.168.59.103:5432/spring-boot-heroku-example
#spring.datasource.username=spring-boot-heroku-example
#spring.datasource.password=spring-boot-heroku-example
#spring.datasource.driver-class-name=org.postgresql.Driver
