spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-163-228-109.compute-1.amazonaws.com:5432/dfcomeboave3jd
    username: fyyknypscirzdg
    password: btRK9jnZj1qcqOrZe8OBdnJjNn

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

---

spring:
  profiles:
    active: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
